[workspace]
resolver = "2"
members = [
    "./volare_engine_layout",
    "./svg_renderer",
    "./image_renderer",
    "./demo",
    "./wasm_bindings",
    "./custom_components",
]

# build command that builds all members
[build]
command = "cargo build --all"