[package]
name = "image_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volare_engine_layout = { path = "../volare_engine_layout" }
image = "0.23"
imageproc = "0.22"
rusttype = "0.9"
bresenham = "0.1.1"

[lib]
name = "image_renderer"
path = "src/lib.rs"