[package]
name = "svg_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volare_engine_layout = { path = "../volare_engine_layout" }

[lib]
name = "svg_renderer"
path = "src/lib.rs"